baseurl = "http://levyflight.github.io"
title = "Levy Flight"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
#disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
    name = "LevyFlight"
    bio = ""
    avatar = "img/avatar.png"


[Params]
    subtitle = " A levy flight through  mutliple subjects" # Subtitle of your site
    description = " John Doe's Personal blog about everything" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget 
    categories = true # Enable "Categories" widget
#    tags = true # Enable "Tags" widget
